$bytes = [System.IO.File]::ReadAllBytes("$PWD\index.html")
$text = [System.Text.Encoding]::UTF8.GetString($bytes)

$b64 = 'ewogICAgImltYWdlcy9kYWtobGEvaGVyby5qcGciOiAiaW1hZ2UgZXNzYS9hY2NldWlsIGRha2hsYS5qcGciLAogICAgImltYWdlcy9kYWtobGEvc2FudGFfbWFyaWFfY29ybmkuanBnIjogImltYWdlIGVzc2EvTOKAmcOpZ2xpc2UgU2FudGEgTWFyaWEgRGVsIENvcm5pLmF2aWYiLAogICAgImltYWdlcy9kYWtobGEvcGhhcmUuanBnIjogImltYWdlIGVzc2EvTGUgcGhhcmUgZGUgRGFraGxhLmpwZyIsCiAgICAiaW1hZ2VzL2Rha2hsYS9hbmNpZW5fcG9ydC5qcGciOiAiaW1hZ2UgZXNzYS9M4oCZYW5jaWVuIHBvcnQgZGUgcMOqY2hlLmpwZyIsCiAgICAiaW1hZ2VzL2Rha2hsYS9sZW1oaWduYXQuanBnIjogImltYWdlIGVzc2EvTGVzIHNpdGVzIGFyY2jDqW9sb2dpcXVlcyBkZSBMZW1oaWduYXQuanBnIiwKICAgICJpbWFnZXMvZGFraGxhL2xhZ3VuZS5qcGciOiAiaW1hZ2UgZXNzYS9MYSBsYWd1bmUgZGUgRGFraGxhLnBuZyIsCiAgICAiaW1hZ2VzL2Rha2hsYS9odWl0cmVzLmpwZyI6ICJpbWFnZSBlc3NhL0xlcyBodcOudHJlcyBkZSBEYWtobGEud2VicCIsCiAgICAiaW1hZ2VzL2Rha2hsYS9mcnVpdHNfbWVyLmpwZyI6ICJpbWFnZSBlc3NhL2xlcyBmcnVpdHMgZGUgbGEgbWVyLndlYnAiLAogICAgImltYWdlcy9kYWtobGEvbWVjaG91aV9zYWhyYW91aS5qcGciOiAiaW1hZ2UgZXNzYS9MZSBtw6ljaG91aSBzYWhyYW91aS5qcGciLAogICAgImltYWdlcy9kYWtobGEvY291c2NvdXNfc2FoYXJpZW4uanBnIjogImltYWdlIGVzc2EvTGUgY291c2NvdXMgc2FoYXJpZW4ud2VicCIsCiAgICAiaW1hZ2VzL2Rha2hsYS90aGVfc2FocmFvdWkuanBnIjogImltYWdlIGVzc2EvTGUgdGjDqSBzYWhyYW91aS5qcGciLAogICAgImltYWdlcy9kYWtobGEvcG9pc3Nvbl9ncmlsbGUuanBnIjogImltYWdlIGVzc2EvcG9pc3NvbiBncmlsbGVzanBlZy5qcGVnIiwKICAgICJpbWFnZXMvZGFraGxhL2N1bHR1cmVfc2FocmFvdWllLmpwZyI6ICJpbWFnZSBlc3NhL0xhIGN1bHR1cmUgc2FocmFvdWllLmpwZyIsCiAgICAiaW1hZ2VzL2Rha2hsYS9oYXNzYW5pYS5qcGciOiAiaW1hZ2UgZXNzYS9MYSBwb8Opc2llIGV0IGxhIG11c2lxdWUgaGFzc2FuaWVzLmpwZyIsCiAgICAiaW1hZ2VzL2Rha2hsYS90aGVfcml0dWVsLmpwZyI6ICJpbWFnZSBlc3NhL0xlcyB0cmFkaXRpb25zIGR1IHRow6kgc2FoYXJpZW4uanBnIiwKICAgICJpbWFnZXMvZGFraGxhL3BlY2hlX3RyYWRpdGlvbi5qcGciOiAiaW1hZ2UgZXNzYS9MYSBjdWx0dXJlIG1hcml0aW1lIGV0IGxhIHDDqmNoZS5qcGciLAogICAgImltYWdlcy9kYWtobGEvZmVzdGl2YWxzLmpwZyI6ICJpbWFnZSBlc3NhL0xlcyBmZXN0aXZhbHMgY3VsdHVyZWxzLmpwZyIsCiAgICAiaW1hZ2VzL2Rha2hsYS9hcnRpc2FuYXQuanBnIjogImltYWdlIGVzc2EvTOKAmWFydGlzYW5hdCBzYWhhcmllbi5qcGciLAogICAgImltYWdlcy9kYWtobGEva2l0ZXN1cmYuanBnIjogImltYWdlIGVzc2EvRmFpcmUgZHUga2l0ZXN1cmYgZGFucyBsYSBsYWd1bmUud2VicCIsCiAgICAiaW1hZ2VzL2Rha2hsYS9kdW5lX2JsYW5jaGUuanBnIjogImltYWdlIGVzc2EvRXhwbG9yZXIgbGEgRHVuZSBCbGFuY2hlLmpwZyIsCiAgICAiaW1hZ2VzL2Rha2hsYS9mbGFtYW50cy5qcGciOiAiaW1hZ2UgZXNzYS9PYnNlcnZlciBsZXMgZmxhbWFudHMgcm9zZXMuanBlZyIsCiAgICAiaW1hZ2VzL2Rha2hsYS9leGN1cnNpb25fZGVzZXJ0LmpwZyI6ICJpbWFnZSBlc3NhL0ZhaXJlIHVuZSBleGN1cnNpb24gZGFucyBsZSBkw6lzZXJ0LmF2aWYiLAogICAgImltYWdlcy9kYWtobGEvaWxlX2RyYWdvbi5qcGciOiAiaW1hZ2UgZXNzYS9WaXNpdGVyIGzigJnDrmxlIGR1IERyYWdvbi5qcGciLAogICAgImltYWdlcy9kYWtobGEvc291cmNlc19hc21hYS5qcGciOiAiaW1hZ2UgZXNzYS9Qcm9maXRlciBkZXMgc291cmNlcyB0aGVybWFsZXMgZOKAmUFzbWFhLndlYnAiLAogICAgImltYWdlcy9kYWtobGEvcGFyY19uYXRpb25hbC5qcGciOiAiaW1hZ2UgZXNzYS9Ew6ljb3V2cmlyIGxlIHBhcmMgbmF0aW9uYWwgZGUgRGFraGxhLndlYnAiLAogICAgImltYWdlcy9kYWtobGEvY291Y2hlcl9sYWd1bmUuanBnIjogImltYWdlIGVzc2EvQWRtaXJlciBsZSBjb3VjaGVyIGRlIHNvbGVpbCBzdXIgbGEgbGFndW5lLmpwZyIKfQ=='
$jsonBytes = [Convert]::FromBase64String($b64)
$jsonStr = [System.Text.Encoding]::UTF8.GetString($jsonBytes)
$replacements = $jsonStr | ConvertFrom-Json

foreach ($prop in $replacements.psobject.properties) {
    $text = $text.Replace($prop.Name, $prop.Value)
}

# Remove the missing Dakhla ones
$text = [regex]::Replace($text, '(?s)[ \t]*<div class="city-card">\s*<div class="city-card-img-wrap">\s*<img src="images/dakhla/(porte_quartier_espagnol|inifaffen_chyaf|aghylas|desert_ocean|gastronomie_nomade)\.jpg"[^>]+>\s*</div>\s*<h3>.*?</h3>.*?</div>\s*', "")

# Remove the Tajine de poisson food-pill from Essaouira
$text = [regex]::Replace($text, '(?s)[ \t]*<div class="food-pill">\s*<img class="food-pill-img" src="images/essaouira/tajine_poisson\.jpg"[^>]+>\s*</div>\s*<div>.*?</div>\s*</div>\s*', "")

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText("$PWD\index.html", $text, $utf8NoBom)
Write-Output "Done Dakhla + Tajine removals!"
